### ISSUE TITLE
[Feature] 9.4 부터 추가된 `.env` 기능 추가하면 좋을것 같아요.

### ISSUE THREAD

**Issue by rhiokim** [yceffort/koa-nextjs-react-typescript-boilerplate#11]
## 설명

9.4 부터 추가된 `.env` 파일을 통한 환경변수 주입을 지원하면 좋을것 같습니다. ☺️

**Comment by yceffort** [comment]
@rhiokim 감사합니다 사랑합니다 추석때 #9 이거하면서 같이 해보겠습니다

**Comment by yceffort** [comment]
https://nextjs.org/docs/api-reference/next.config.js/environment-variables
